package mytool.backend

import groovy.transform.CompileStatic
import mytool.collector.xueqiu.v5.XueqiuV5DataCollector
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.web.bind.annotation.GetMapping

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */

import org.springframework.web.bind.annotation.RestController

@RestController
@CompileStatic
class MyRestController {

    @Autowired
    CorpListService corpListService

    @Autowired
    TaskService taskService

    @GetMapping("corpList")
    List<String> corpList() {
        return corpListService.corpList()
    }

    @GetMapping("taskInfos")
    List<TaskService.TaskInfo> taskInfoList() {
        return taskService.taskInfoList()
    }

    @GetMapping("cancel")
    boolean cancel(String id) {
        return taskService.cancel(id)
    }

    @GetMapping("collect")
    TaskService.TaskInfo collect() {
        File folder = new File("d:\\openstock\\xueqiuv5\\raw")
        XueqiuV5DataCollector dc = new XueqiuV5DataCollector(folder)
        dc.cookie("xq_a_token=0f82d04ce8d5080cc888fa50c97b841494e931dd;")
        dc.types(XueqiuV5DataCollector.balance, XueqiuV5DataCollector.income, XueqiuV5DataCollector.cash_flow)
        dc.pauseInterval(1 * 1000)
        List<String> corpCodeL = this.corpListService.corpList()
        dc.corpCodes(corpCodeL)
        return taskService.addTask("collect", dc)

    }
}
