package mytool.backend

import mytool.collector.xueqiu.v5.XueqiuV5DataCollector

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */

import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController

@RestController
class MyRestController {

    @GetMapping("collector")
    String hello(@RequestParam(value = "name", defaultValue = "xueqiu") String name) {
        File folder = new File("d:\\openstock\\xueqiuv5\\raw");
        XueqiuV5DataCollector dc = new XueqiuV5DataCollector(folder)
        dc.types(XueqiuV5DataCollector.balance, XueqiuV5DataCollector.income, XueqiuV5DataCollector.cash_flow)

        dc.pauseInterval(1 * 1000);
        List<String> corpCodeL = ["000001"]
        dc.corpCodes(corpCodeL)
        dc.execute()
        return "ok"
    }
}
