package mytool.backend.rest

import groovy.transform.CompileStatic
import mytool.backend.service.ConfigService
import mytool.backend.service.CorpListService
import mytool.backend.service.DataService
import mytool.backend.service.TaskService
import mytool.collector.database.ReportDataAccessor
import mytool.collector.database.Tables
import mytool.collector.util.EnvUtil
import mytool.collector.wash.WashedFileLoader
import mytool.collector.xueqiu.v5.XQV5DataCollector
import mytool.collector.xueqiu.v5.XQV5DataWasher
import mytool.util.jdbc.JdbcAccessTemplate
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestParam

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */

import org.springframework.web.bind.annotation.RestController

import java.nio.charset.Charset
import java.sql.Connection

@RestController
@CompileStatic
class MyRestController {

    @Autowired
    CorpListService corpListService

    @Autowired
    TaskService taskService

    @Autowired
    ConfigService configService

    @Autowired
    DataService dataService

    @GetMapping("corpList")
    List<String> corpList() {
        return corpListService.corpList()
    }

    @GetMapping("taskInfos")
    List<TaskService.TaskInfo> taskInfoList() {
        return taskService.taskInfoList()
    }

    @GetMapping("cancel")
    boolean cancel(String id) {
        return taskService.cancel(id)
    }

    @GetMapping("collect")
    TaskService.TaskInfo collect() {
        File folder = configService.getDataFolder("xueqiuv5", "raw")
        XQV5DataCollector dc = new XQV5DataCollector(folder)
        dc.cookie(configService.getXueQiuToken())
        dc.types(XQV5DataCollector.balance, XQV5DataCollector.income, XQV5DataCollector.cash_flow)
        dc.pauseInterval(1 * 1000)
        List<String> corpCodeL = this.corpListService.corpList()
        dc.corpCodes(corpCodeL)
        return taskService.addTask("collect", dc)

    }

    @GetMapping("wash")
    TaskService.TaskInfo wash() {
        File folder = configService.getDataFolder("xueqiuv5", "raw")
        File folder2 = configService.getDataFolder("xueqiuv5", "washed")
        XQV5DataWasher w = new XQV5DataWasher(folder, Charset.forName("UTF-8"), folder2);
        w.types(XQV5DataCollector.balance, XQV5DataCollector.income, XQV5DataCollector.cash_flow)

        return taskService.addTask("wash", w)
    }

    @GetMapping("load")
    TaskService.TaskInfo load() {
        File folder = configService.getDataFolder("xueqiuv5", "washed")
        ReportDataAccessor reportDataAccessor = dataService.getReportDataAccessor()
        WashedFileLoader.WashedFileLoadContext flc = new WashedFileLoader.WashedFileLoadContext(reportDataAccessor);
        return taskService.addTask("load", {
            new WashedFileLoader().load(folder, flc);
        })
    }

    @GetMapping("sql")
    List<List> sql(@RequestParam(name = "sqlId") String sqlId) {
        return dataService.executeQueryBySqlId(sqlId)
    }


}
