package mytool.backend.controller

import groovy.transform.CompileStatic
import mytool.backend.ChartData
import mytool.backend.service.ChartService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */

@RestController
@CompileStatic
@RequestMapping("/v1/chart")
class ChartRestController {

    @Autowired
    ChartService chartService

    @GetMapping("chart")
    ChartData chart(@RequestParam(name = "corpId", required = true) String corpId,
                    @RequestParam(name = "provider", required = true) String provider,
                    @RequestParam(name = "metric", required = false) String metric,
                    @RequestParam(name = "report", required = false) String report) {

        switch (provider) {
            case "metric":
                assert metric, "metric is null"
                return chartService.getChartData(corpId, metric)
            case "report":
                assert report, "report is null"
                return chartService.getChartDataByReport(corpId, report)
        }
    }


}
