package mytool.backend.controller

import groovy.transform.CompileStatic
import mytool.backend.service.ConfigService
import mytool.backend.service.CorpListService
import mytool.backend.service.DataService
import mytool.backend.service.TaskService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */

@RestController
@CompileStatic
@RequestMapping("/v1/sql")
class SqlRestController {

    @Autowired
    CorpListService corpListService

    @Autowired
    TaskService taskService

    @Autowired
    ConfigService configService

    @Autowired
    DataService dataService

    @GetMapping("sql")
    List<List> sql(@RequestParam(name = "sqlId") String sqlId) {
        return dataService.executeQueryBySqlId(sqlId)
    }

}
