/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package mytool.server

import org.junit.jupiter.api.Test

class MessageUtilsTest {
    @Test void testGetMessage() {

    }
}
